### ISSUE TITLE
Développement du profil utilisateur

### ISSUE THREAD

**Issue by lelafontant** [ceduni/lino#15]

**Comment by benhoangquan** [comment]
Done halfway with the front end part. Missing integration with backend

- Achievement is not defined yet => Point to discuss.
- Notification preferences need to be saved somewhere, either locally or database; and it's not well defined too. => Point to discuss.

**Comment by benhoangquan** [comment]
on the newest commit, with guest login, there is no user information. But profile page required user information to display, so with guest login, we run into null value. 

Suggested fixes:

- Either have guest info as default value
- Or have change the profile page to adapt to null value. 

@lelafontant @NathanRazaf thought?

**Comment by benhoangquan** [comment]
remove saved water and carbon savings
add tracked keyword

**Comment by NathanRazaf** [comment]
> on the newest commit, with guest login, there is no user information. But profile page required user information to display, so with guest login, we run into null value.
> 
> Suggested fixes:
> 
> * Either have guest info as default value
> * Or have change the profile page to adapt to null value.
> 
> @lelafontant @NathanRazaf thought?

Just don't activate the button to access the profile when the user is a guest lol
Like, we can put a login button instead

**Comment by NathanRazaf** [comment]
Why tf am I assigned to that?
