### ISSUE TITLE
Get All Book Boxes method

### ISSUE THREAD

**Issue by benhoangquan** [ceduni/lino#23]
Helloooo, 

@NathanRazaf, peux tu ajouter une methode pour avoir tous les book boxes pour que je peux afficher sur Main screen? Je check dans README de backend et je pense que cette methode n'existe pas. Maybe I'm wrong?

**Comment by NathanRazaf** [comment]
Yo,

@benhoangquan jviens de push la méthode pour chercher des bookboxes, tu peux utiliser ça et mettre 0 arguments pour avoir toutes les bookboxes
