### ISSUE TITLE
Développer la barre de recherche

### ISSUE THREAD

**Issue by lelafontant** [ceduni/lino#9]

**Comment by benhoangquan** [comment]
Need to put the search algo of the back end to make it functional.

According to @lelafontant on Discord: 

> Vous pourrez optimiser la recherche lorsqu'on aura complété les fonctionnalités de base.
Voilà quelques pistes d'amélioration (pour après): Le full text search offert par MongoDB (https://www.mongodb.com/resources/basics/full-text-search), des algorithmes de distance/similarité (Levenshtein, Jaro–Winkler, similarité cosinus...), librairies NLP

**Comment by benhoangquan** [comment]
Nathan — Today at 7:13 PM
quand tu fais un search sur le mapscreen ça devrait chercher des livres, quand tu fais un search sur le threadscreen ça recherchera des threads

Quan — Today at 7:16 PM
Right, alors je vais faire le search bar reusable et je vais mettre un callback function comme argument pour que tu peux mettre le search function soit pour les threads ou soit pour les livres
